### ISSUE TITLE
Adapting for for stereo-vision

### ISSUE THREAD

**Issue by r-ym** [rdouguet/hikrobot_mv_ros#1]
Hello,
I am currently trying to adapt this package for binocular vision with two cameras. Still new to ROS and would love to know what would be the best way to go about that.

Sincerely,

**Comment by rdouguet** [comment]
Hello Raman,

Sorry for the late response, I was on vacation :) I am also starting with ROS since the beginning of the year so I 'm not sure to have the best way...

On my system, I use 2 different cameras so I have one specific node for each camera. A quickly solution in your case, could be use 2 different ros packages for each camera (you duplicate this package with a other name). But to capture the image in the same time, you need to use a signal synchronisation on the input trigger.

On other solution is to change the the hikrobot_mv_driver.cpp file to capture and publish the image of each camera. The function MV_CC_EnumDevices allows to get the device list. In my package, I forced to use the first device by setting the index variable to 0 but you have the possility to open and configure this two camera in the same node...

I will be interested to know your solution .

Thanks,
Ronan

**Comment by r-ym** [comment]
Hey Ronan,

No worries:) hope it was relaxing. My team at work actually ended up developing a package to get it to work, and we happened to also decide on the camera indexing method via MV_CC_EnumDevices. Will be closing the issue now, thank you for your time!

Cheers
